services:
  web:
    build: beusp
    ports:
      - 8080:80
    networks:
      - beusp
    image: zynthasius/beusp:alpine
  api:
    build:
      context: .
      dockerfile: beusproxy.Dockerfile
    volumes:
      - type: bind
        source: ./shared
        target: /hpage/shared
    networks:
      - beusp
    env_file: .env
    image: zynthasius/beusproxy:alpine
  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    volumes:
      - type: bind
        source: ./shared
        target: /hpage/shared
    networks:
      - beusp
    env_file: .env
    image: zynthasius/beusproxy:bot-alpine

networks:
  beusp: